### ISSUE TITLE
Seemingly invalid JDBC URL seems to work when trying to get a connection from ComboPooledDataSource

### ISSUE THREAD

**Issue by anandgopinath** [swaldman/c3p0#107]
I'm trying to stop a scenario where the JDBC URL is invalid. If I do something like this:
```
ComboPooledDataSource cpds;
...
cpds.setJdbcUrl("jdbc:mysql://localhost:3306,my_db");
// and then 
Connection conn = cpds.getConnection();
// I get a Connection object. 
```
When the JDBC URL is something like 
`jdbc:mysql://localhost:3306,my_db`

No error is thrown. I would have expected a `SQLException` of some sort given that the URL is invalid. A valid URL would be something like:
`jdbc:mysql://localhost:3306/my_db` 
but I suspect because the JDBC URL allows for multiple hosts, the `getConnection` call does not fail with an invalid URL. If I replace the `,` with `;` I get a `SQLException` saying that it cannot parse the port value. How do I go about validating a JDBC URL that isn't valid (i.e. `jdbc:mysql://localhost:3306,my_db`)?

I'm using the 0.9.5.2 version of the library.

**Comment by swaldman** [comment]
c3p0 just delegates this to the`Driver` via `DriverManager`. If your driver is happy to accept a JDBC URL, so is c3p0. I don't think c3p0 can try to offer stricter validation, since Drivers are free to specify any URL format they like.
