### ISSUE TITLE
com.mchange.v2.c3p0.cfg.C3P0ConfigXmlUtils.warnCommonXmlConfigResourceMisspellings is very slow

### ISSUE THREAD

**Issue by chinhodado** [swaldman/c3p0#121]
When using Hibernate with c3p0, during startup, c3p0 takes very long to configure. Here's the profile result:

![image](https://user-images.githubusercontent.com/1388219/48956295-4925b500-ef20-11e8-8203-0a2266d59afc.png)

c3p0 is taking about 700ms to `warnCommonXmlConfigResourceMisspellings()`

**Comment by swaldman** [comment]
from C3P0ConfigXmlUtils.java:

```java
    // its an ugly way to do this, but since resources are not listable...
    //
    // this is only executed once, and does about 40 tests (for now)
    // should I care about the cost in initialization time?
    //
    // should only be run if we've checked for the correct file, but
    // not found it
```

Maybe I should have cared!

I'm just going to disable this for now. It's just trying to be generous about helping people debug close-but-not-quite-right names for `c3p0-config.xml`. But it's apparently not being very generous on startup time.

Thanks!

See https://github.com/swaldman/c3p0/commit/8d3e2339fee3a81f6f45dcee86e24fecfe7f4e17

**Comment by chinhodado** [comment]
Wow I don't even remember making this issue 5 years ago.

Thanks for the fix!
