### ISSUE TITLE
License under GNU LGPL v>=2.1 (LGPL-2.1-or-later)?

### ISSUE THREAD

**Issue by bernhardreiter** [swaldman/c3p0#133]
Hello,
may I suggest to extend the licensing from `LGPL-2.1-only` to `LGPL-2.1-or-later`?

This will keep the freedom protection of the license, but makes it more compatible.
While at it, using the SPDX identifiers like recommended in https://reuse.software/practices/2.0/ can make it easier for others to see the licensing information.

Best Regards,
Bernhard

**Comment by swaldman** [comment]
Done!

Thanks.

https://github.com/swaldman/c3p0/commit/d269061273a3d953680c5861a08418473225b602
