### ISSUE TITLE
[FALSE POSITIVE] mchange.com domain snatched?

### ISSUE THREAD

**Issue by ljader** [swaldman/c3p0#140]
When I enter "mchange.com" I got redirected to www.sbt-ethereum.io

Was the domain snatched?
If yes, maybe you should update the README then?

**Comment by ozkanpakdil** [comment]
I think you got some kind of virus. when I check mchange works.

**Comment by ljader** [comment]
Hi @ozkanpakdil , thanks very much for your reply.

Indeed when I open a browser with the cache disabled, the mchange.com address works as expected.
However with cache enabled, the 301 redirect still occurs.

I think Steve had some sort of experiments with the domain settings (it's his project after all https://github.com/swaldman/sbt-ethereum ) ,
and it happens that my browser got and cached the 301 redirect.

I'm closing this ticket, however I'll leave the original description if someone experiences the same thing.
