### ISSUE TITLE
p0 properties

### ISSUE THREAD

**Issue by praveenkjvs** [swaldman/c3p0#142]

**Comment by swaldman** [comment]
???

**Comment by praveenkjvs** [comment]
@swaldman sorry for leaving this open and unattended. I will close this, since I do not remember the full context on why I opened this issue.

PS:I was working on a project that put lot of stress on the connection pool (more like stress / reliability testing) and found couple of issues. but then alas, i had to move on to another project and lost track of the issues that I discovered.
