### ISSUE TITLE
Licence file does not exist in the source jar

### ISSUE THREAD

**Issue by ankitdigarsey2** [swaldman/c3p0#167]
Hello contributors, we (Backup & DR team at Google Cloud) are using [maven source plugin](https://maven.apache.org/plugins/maven-source-plugin/usage.html) to pull the source jar for c3p0 library but can not seem to find EPL 1.0 license files in the source jar. Could you please add the licenses in the source jar for the c3P0 library? Please let me know if you need any details. Thanks !

**Comment by swaldman** [comment]
OK.

https://github.com/swaldman/c3p0/commit/adff50803a566d1a4ee189588d81404ae8233927
