### ISSUE TITLE
Compatibility with JDK 17

### ISSUE THREAD

**Issue by test-account1233** [swaldman/c3p0#173]
Hi @swaldman,

I wasn't able to find information regards compatibility with JDK 17, could you please share current state is it compatible with JDK 17 or not? (If it's compatible please share version as well)

Best Regards,
Hrach

**Comment by swaldman** [comment]
It should be compatible with all version of java, from Java 6 on for the 0.9.5+ series, from Java 7 on for the 0.10.0 series. If you run into glitches on newer javas, let me know. I run c3p0 under Java 17 for my own projects.
