### ISSUE TITLE
c3p0 0.9.2.1 - java.lang.AbstractMethodError: com.mchange.v2.c3p0.impl.NewProxyResultSet.isClosed()

### ISSUE THREAD

**Issue by kappolo** [swaldman/c3p0#18]
I'm using c3p0 0.9.2.1 and whenever I try to call a ResultSet.isClosed() on a non-null, still open result set, I get the following exception:

java.lang.AbstractMethodError: com.mchange.v2.c3p0.impl.NewProxyResultSet.isClosed()

I know it sounds odd, but I have been using c3p0 (always the same version) for quite a while and this exception started to appear only at some point. I couldn't isolate a reason or change for this to happen.
It seems that using 0.9.5-pre5 solves the issue, but as it's production code I would like to keep using a stable version. 

Any hints or explanations of this issue?
Thanks

**Comment by lslxgxh** [comment]
l had the same problem，I added the right package but it didn't work.

**Comment by swaldman** [comment]
you get this error using c3p0-0.9.5.2?

**Comment by lslxgxh** [comment]
yes,now I I don't know what I should do.

**Comment by swaldman** [comment]
if it is precisely this error...

    java.lang.AbstractMethodError: com.mchange.v2.c3p0.impl.NewProxyResultSet.isClosed()

...i think it very likely you have an old version in your `CLASSPATH` that is interfereing.

**Comment by lslxgxh** [comment]
I try to delete the dependency in pom.xml. The error still exists.

**Comment by swaldman** [comment]
I don't know. That depends on how you are setting up your application, downloading its dependencies, etc. Ultimately you want c3p0-0.9.5.2.jar and mchange-commons-java-0.2.11.jar in your application's effective `CLASSPATH`.

**Comment by lslxgxh** [comment]
Thank you very much for your extensive explanation,
I think I already know how to try.

**Comment by swaldman** [comment]
You are very welcome. I hope that it works out.

**Comment by RexCN** [comment]
太棒了，帮到了我。

**Comment by harishsalez** [comment]
@swaldman 

Thank you, It is working fine.

> I don't know. That depends on how you are setting up your application, downloading its dependencies, etc. Ultimately you want c3p0-0.9.5.2.jar and mchange-commons-java-0.2.11.jar in your application's effective `CLASSPATH`.
