### ISSUE TITLE
C3P0 should allow use of injected Executor

### ISSUE THREAD

**Issue by mrossi975** [swaldman/c3p0#41]
hi,
This is not really an issue, more of a feature request.

C3P0 creates a lot of threads to manage connection pools.
It uses java.util.Timer to perform certain tasks and it seems to create its own pools of threads.

I would argue that such situation is not optimal.

It should be possible to instantiate C3P0 passing your own instance of ScheduledThreadPoolExecutor and timer-like tasks should be scheduled on it rather than on the less efficient java.util.Timer.

I am attaching a screenshot that shows how many threads are created by C3P0 with only 4 connections pools.

If the project leads believe this to be a worthy effort I can consider contributing it myself.

thanks,
Michele

![c3p0_threads](https://cloud.githubusercontent.com/assets/3889052/5277779/e342a7dc-7ad1-11e4-9872-f75d4cc171be.png)

**Comment by swaldman** [comment]
Ha! Why, you are the same @mrossi975 I just responded to here! Anyway, pretty much exactly as sketched out a decade ago above, you can now (as of c3p0-0.10.x) substitute new or existing `Executor` instances for c3p0's default Thread pool. See https://github.com/swaldman/c3p0/issues/76
