### ISSUE TITLE
Specifying Config instance

### ISSUE THREAD

**Issue by gitblit** [swaldman/c3p0#45]
In my other issue (#44) I mentioned my current trivial config.

What I really want to do is provide a TypeSafe Config *object* to the `DataSources` class - or some other as-convenient class.  I do not want to rely on classpath loading of a configuration file as I have my own Config design.  Alternatively, I could be happy with being able to specify a properties/xml/hocon url.

I don't see a clear way to accomplish this right now.
Do you have any suggestions?

**Comment by swaldman** [comment]
Boy, if what you want is customizable configuration, c3p0 is your library. Sometimes I think c3p0 is a skein of elaborate configuration code with a ConnectionPool tacked on as an afterthought.

Some ideas:

1. The only one, alas, well documented in c3p0 docs [TODO: fix that] is for the XML format. You can set the system property `com.mchange.v2.c3p0.cfg.xml` to a filesystem path, see http://www.mchange.com/projects/c3p0/#other-properties

2. c3p0 supports the typesafe/HOCON config conventions of letting user-specified files replace the standard `application.{conf,json,properties}`, which c3p0 supports. Note that settings in a classloader `/c3p0.properties` file will override settings in `application.*`, so they will override settings in your user-specified replacement too. Don't put any settings you don't want bullying ahead in `/c3p0.properties` (or don't include that file in your CLASSPATH at all). The supported HOCON-defined system properties are `config.file`, `config.resource`, and `config.url`. See https://github.com/typesafehub/config#standard-behavior

3. If you were terribly ambitious, you could define an arbitrary [com.mchange.v2.c3p0.cfg.C3P0ConfigFinder](http://www.mchange.com/projects/c3p0/apidocs/index.html), public with a no-arg constructor, and set the system property `com.mchange.v2.c3p0.cfg.finder` to the fully qualified name of that class. Note that your `C3P0ConfigFinder` will replace any XML file config (which is loaded by this mechanism), unless you design your class to include that.

4. If you want your config to be maintained in a typesafe Java object, just define such an object conformant to JavaBeans naming conventions. That is, ensure that there are getters for all the config elements you specify of the form `T getBlah()` for a config param called blah of type T. All of the [JavaBeans-style properties](http://www.mchange.com/projects/c3p0/#configuration_properties) are appropriate parameters. Then, to apply your config, use the following incantantion

````
import com.mchange.v2.c3p0.ComboPooledDataSource;
import com.mchange.v2.beans.BeansUtils;

...

// first, create a DataSource whose configuration has been defined by
// all the various c3p0 config forming mechanisms.
ComboPooledDataSource cpds = new ComboPooledDataSource();

 //instantiate your custom JavaBean here
MyJavaBeanConfig myConfigBean = findMyConfigBean();

// now bind the values from your config object to the DataSource
BeansUtils.overwriteAccessibleProperties( myConfigBean, cpds );

// yay! you are done.
````

If you want to omit some properties from the overwriting (to avoid harmless log messages about unsettable properties, mostly), you can overwrite properties with something like...

````
import java.util.List;
import java.util.Arrays;

...

List<String> ignoreProps = Arrays.asList( "class", "configVersion", "whatever" );
BeansUtils.overwriteAccessibleProperties( myConfigBean, cpds, ignoreProps. );
````

For more information, [BeansUtils](https://github.com/swaldman/mchange-commons-java/blob/master/src/main/java/com/mchange/v2/beans/BeansUtils.java) in mchange-commons-java.

I hope this helps!

**Comment by gitblit** [comment]
Perfect.  Thanks so much for taking the time to write up such a detailed answer.
