### ISSUE TITLE
Add a hook when the pool fails to acquire a connection

### ISSUE THREAD

**Issue by martins1930** [swaldman/c3p0#50]
Hi, 
My business requirement is: "I need to send an email when something goes wrong with the database".
How can I do that?

I created a customized ConnectionTester (http://www.mchange.com/projects/c3p0/#connectionTesterClassName) that sends an email when an error arises, but the ConnectionTester is only invoked after the Connection is acquired from the database.
For example the ConnectionTester is not invoked when:
A) The ComboPooledDataSource is configured with a user with a misconfigured password.
B) The ComboPooledDataSource is configured with a user that does not exists in the database.

Can we add a new method to ConnectionCustomizer interface (http://www.mchange.com/projects/c3p0/#connectionCustomizerClassName) ?
For example add a method called: 

```java
    public void onAcquireError( Connection c, Throwable t) throws Exception;
```
This method should be invoked when is not possible to acquire the Connection.

Do you see any alternatives to dealing with the scenarios A) and B) ?

Regards,
Martín.

Note: I'm working with mysql.

**Comment by swaldman** [comment]
Hi,

Definitely don't use a ConnectionTester for this, Connections are tested frequently under all kinds of conditions, they are not remotely an event hook, and as you've noticed there's never any Connection to be tested when there's been an acquisition failure.

As you suggest, a specific event hook of some sort could be added for acquisition failures, and might at some point. (Early in c3p0's development history there was nascent support was added for a variety of event hooks. But the threading complications of that weren't worth the trouble.)

For now, a perfectly good solution to the problem you face would simply be to poll for acquisition failures.

```java

// alternatively you could use a java.util.Timer
class AcquisitionFailureWatcher extends Thread {
   volatile boolean shouldStop = false;

   // only read or modified by this Thread
   PooledDataSource pds;
   Thowable last = null;

   AcquisitionFailureWatcher( PooledDataSource pds ) {
        this.pds = pds;
   }

   public void run() {
       try {
          while (! shouldStop ) {
             Throwable acquisitionFailure = pds.getLastAcquisitionFailureDefaultUser();
             if ( acquisitionFailure != last ) {
                 emailAcquisitionFailure( acquisitionFailure ); // assuming this method somewhere
                 last = acquisitionFailure;
             }
            Thread.sleep( 60000 );
          }
       } catch (InterruptedException e) {
            // assuing a logger somewhere
            logger.warn( "Acquisition failure watcher interrupted and terminated!", e);
       }
   }
}

PooledDataSource myDataSource = ...; // however you create your c3p0 DataSource
AcquisitionFailureWatcher afw = new AcquisitionFailureWatcher( myDataSource );
afw.start();
```

Note that I'm presuming that you are only working with a default user. To capture acquisition failures for any auth, you'd need to `getAllUsers()` and maintain and test a HashMap of last failures on a per-user basis.
 
Perhaps it's not as simple as you'd like, but it avoids the hazards of, say, having c3p0-internal Threads get tied up in network-intensive e-mail sending (the sort of possibility that led me to drop early event support). And it should work great.

**Comment by martins1930** [comment]
Hi swaldman!
I'll implement the solution that you say.
Thank you!!
