### ISSUE TITLE
Is there an easy way to print out c3p0 configuration?

### ISSUE THREAD

**Issue by GlenKPeterson** [swaldman/c3p0#56]
I've been changing my c3p0 config parameters in my JPA/Hibernate persistence.xml file all day without seeing any noticeable difference in performance.  I'd like to tell c3p0 to print it's configuration so I can see that the parameters I'm setting are actually the ones being used.  Also that I'm spelling them correctly (preferredTestQuery vs. preferred_test_query).  Thanks!

**Comment by swaldman** [comment]
c3p0 DataSources dump their config into logs at INFO level upon pool initialization (usually the first time `getConnection()` is called).

**Comment by swaldman** [comment]
(If you want to get the config manually, you can call `toString(true)` on a `ComboPooledDataSource`, and you'll get a description including the DataSource's config.)

**Comment by GlenKPeterson** [comment]
Thank you - I'm all set now!
