### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by henrydev10** [swaldman/c3p0#68]
Hi.
Where can I find the process for contributing new functionality?

Thanks,
Henry.

**Comment by swaldman** [comment]
if you send a pull request, i'll take a look. if you want some feedback on what you plan to do first, let me know.

before accepting a pull request, i'll ask you to consent by e-mail to granting nonexclusive perpetual rights the code contributed, under c3p0's current licensing terms but also the right to relicense it under alternative terms. (this came up when we changed from strict LGPL v2 to dual licensing LGPL/EPL, i had to contact past contributors to get their assent, i'd prefer to avoid that kind of thing going forward.)

**Comment by henrydev10** [comment]
No problem about license, I will send an email. Please send me a template of what to send.
Regarding what I planned to do:
Currently, if using ComboPooledDataSource (abstract actually) getting connections not from the default pool but by user / pass - there is no elaborated MBeans for each pool as it is for the default connection pool in the data source.
I wanted to add this functionality.
WDYT?

**Comment by henrydev10** [comment]
Seems like there was a problem with the connection pool name I gave. This functionality already exists.
