### ISSUE TITLE
Properties configuration file problem

### ISSUE THREAD

**Issue by Nips** [swaldman/c3p0#72]
Hi,

I'm currently using C3P0 version 0.9.5.2 in a project of mine. When I set the following property "c3p0.extensions.timezone=HKT" in the c3p0.properties I get the warning message "WARNING: Unknown c3p0-config property: extensions.timezone" in runtime.

So to my understanding the property is not being set properly since the timezone continues set to default Greenwich Time.

Can it be a problem on the C3P0Config.java? I saw that line 59 does not include a "." after "extensions" string, causing it to read the property suffix as ".timezone=HKT" instead of "timezone=HKT". Not sure if it helps the suggestion.

At this point I don't know at else to do to fix the property file. Google does not help on this either.

Many thanks.

**Comment by swaldman** [comment]
So, I can't reproduce this.

If you'll forgive my using a Scala REPL to check, I define c3p0.properties as

    c3p0.extensions.timezone=HKT

then...

```
Welcome to Scala version 2.11.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_31).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import com.mchange.v2.c3p0._
import com.mchange.v2.c3p0._

scala> import scala.collection.JavaConversions._
import scala.collection.JavaConversions._

scala> val cpds = new ComboPooledDataSource()
May 17, 2016 3:05:28 PM com.mchange.v2.log.MLog 
INFO: MLog clients using java 1.4+ standard logging.
May 17, 2016 3:05:28 PM com.mchange.v2.c3p0.C3P0Registry 
INFO: Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
cpds: com.mchange.v2.c3p0.ComboPooledDataSource = com.mchange.v2.c3p0.ComboPooledDataSource[ identityToken -> 2rvy129g1hhckzcihff90|75995362, dataSourceName -> 2rvy129g1hhckzcihff90|75995362 ]

scala> cpds.getExtensions().asInstanceOf[java.util.Map[String,String]].toMap
res0: scala.collection.immutable.Map[String,String] = Map(timezone -> HKT)
```

I'm guessing you have more than one version of c3p0 somewhere in your application's effective CLASSPATH or in your Maven/Ivy dependency graph, and you are getting the wrong version.

The first thing to verify, in your logs, is that you get a message at INFO like this:

    INFO: Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]

and the version is what you expect.

**Comment by Nips** [comment]
@swaldman you are right.

It seams I had two different versions on my POM file. So now I tried with the latest version 0.9.5.2 and the property was loaded correctly.

I still continue to see the dates in UTC but for sure is related to another problem, maybe the DB settings or the driver itself.

Many thanks for the quick help :)

**Comment by swaldman** [comment]
i'm glad it worked out! are you using the extension value to initialize Connections in a ConnectionCustomizer?

**Comment by Nips** [comment]
I saw someone in stackoverflow suggesting that exactly. But then I went to C3P0 website to check it, but from the example could not understand how to do it.

I mean I know how to create the class and change the configuration file. What I don't know is how to set the extension value on the java.sql.Connection variable.

**Comment by swaldman** [comment]
[This example](https://github.com/swaldman/c3p0/blob/master/src/java/com/mchange/v2/c3p0/example/InitSqlConnectionCustomizer.java) might be a good one to work from.

You just extend [AbstractConnectionCustomizer](http://www.mchange.com/projects/c3p0/apidocs/com/mchange/v2/c3p0/AbstractConnectionCustomizer.html), override the appropriate method (probably `onCheckOut(...)` or `onAcquire(...)`), and find the extension value with `extensionsForToken(...)`. Note that you have the token value that you need because it is passed as an argument to all the `ConnectionCustomizer` methods.

To make it take effect, you set the config property [connectionCustomizerClassName](http://www.mchange.com/projects/c3p0/#connectionCustomizerClassName) to the fully-qualified class name of the class you have defined (and make sure that class is available to your application).

**Comment by Nips** [comment]
Thanks a lot for your help @swaldman!

Indeed that example helped and I was able to set a default TimeZone for the Java Virtual Machine.
