### ISSUE TITLE
DataSources.unpooledDataSource(...) will never throw a SQLException

### ISSUE THREAD

**Issue by Neiko2002** [swaldman/c3p0#74]
There are some methods with the "throws SQLException" statement that will never throw such an exception. It certainly does not hurt to have them, but the code becomes unclean.

**Comment by swaldman** [comment]
It preserves the ability to change the implementation in ways that might provoke an SQLException without breaking client code.

Broadly speaking, c3p0 conforms to the JDBC convention of presenting interfaces (in the general sense of the term, of course DataSources is a class) that throw SQLExceptions, and code that interacts with it should have strategies for handling SQLExceptions should they occur.
