### ISSUE TITLE
Connection.createArrayOf() throws java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by mrgitTS** [swaldman/c3p0#88]
Full message is
_ java.lang.AbstractMethodError: com.mchange.v2.c3p0.impl.NewProxyConnection.createArrayOf(Ljava/lang/String;[Ljava/lang/Object;)Ljava/sql/Array; _

Class NewProxyConnection was in version 9.2.1 , no longer present in version 9.5.2
What am I missing and need to learn?
Thanks, regards
Massimo

**Comment by swaldman** [comment]
NewProxyConnection is a code-generated class, so you won't find it in the source code in the repository. (You can see how it gets generated [here](https://github.com/swaldman/c3p0/blob/master/src/java/com/mchange/v2/c3p0/codegen/JdbcProxyGenerator.java).)

If you want to see the source including the codegenerated files, you can download the [source jar](https://search.maven.org/remotecontent?filepath=com/mchange/c3p0/0.9.5.2/c3p0-0.9.5.2-sources.jar). I'll attach the generated `NewProxyConnection.java` for 0.9.5.2. It includes
```java
      public synchronized Array createArrayOf(String a, Object[] b) throws SQLException
      {...}
```   
I think it likely that there is an older version of c3p0 in your classpath or dependencies, and you are accidentally using that.

(Sorry, github made me add a `.txt` extension to attach the file, it wouldn't accept a `.java` file as attachment.)

[NewProxyConnection.java.txt](https://github.com/swaldman/c3p0/files/847987/NewProxyConnection.java.txt)

**Comment by swaldman** [comment]
(If you check your logs, c3p0 dumps at INFO its version when the first Connection pool you define is initialized. You might look there to see the effective version within the app.)

**Comment by mrgitTS** [comment]
Steve, thank you for your help.
In fact Hibernate 5.0.9 includes c3p0-0.9.2.1.jar , so once its inizialization is done and my code which uses Prepared Statements kicks in, c3p0-0.9.5.2.jar is ignored.
Attached you may find a log file to document what's happening:
firstly when lib/c3p0-0.9.2.1.jar is present, with or without lib/c3p0-0.9.5.2.jar being there
lastly when only lib/c3p0-0.9.5.2.jar is available
[c3p0.txt](https://github.com/swaldman/c3p0/files/850164/c3p0.txt)

I read somewhere that older c3p0 does not support JDBC4, so createArrayOf() cannot be used.
If so, I am afraid we must upgrade Hibernate in order to get newer c3p0.
Please note that the failing application does mass updates so it is not using Hibernate, however Hibernate is our standard framework and for this application, as anywhere else, it is used to get a secure connection to Postgres.

**Comment by mrgitTS** [comment]
Steve, please bear with me.
My comment made a few hours ago was somewhat careless.
Further testing lead me to fix the classpath, so access to c3p0-0.9.5.2.jar is now correctly handled.
Apologies.
The application however is now crashing a bit later, possibly due to a missing class, named MConfig.
Attached is another file with details.
[c3p0_bis.txt](https://github.com/swaldman/c3p0/files/850806/c3p0_bis.txt)

The crashing class does not import MConfig explicitly, so it probably assumes it must be in one of the imported packages.
Thank you very much for your attention
regards
Massimo

**Comment by swaldman** [comment]
It's very likely that the same source as the outdated c3p0 also provides an outdated version of its transitive dependency, `mchange-commons-java` (where `MConfig` should live).

c3p0-0.9.5.2 declares version 0.2.11 of that library as its dependency. That or any more recent version would be fine. Earlier versions will almost certainly not be fine.

**Comment by mrgitTS** [comment]
All right.  Version 0.2.12 is fine.  Thank you again.
Keep up the good work.
I'll close the issue asap, once I'm finished with testing.

**Comment by swaldman** [comment]
I'm gonna close this one! I hope that's okay, feel free to say so if not.
