### ISSUE TITLE
force_kill_acquires should be in finally

### ISSUE THREAD

**Issue by rscadrde** [swaldman/c3p0#90]
To avoid wrong information coming out of  isForceKillAcquiresPending

force_kill_acquires = false

should be moved to finally block.

**Comment by swaldman** [comment]
Hi,

This issue was fixed (with your help) as of v0.9.5.4.

Thanks!

https://github.com/swaldman/c3p0/commit/5a9b0ebc331e3a3e6f512cd551aed25c19f0beef
