### ISSUE TITLE
Docs (wrongly?) indicate ComboPooledDataSource implements AutoCloseable

### ISSUE THREAD

**Issue by lsowen** [swaldman/c3p0#94]
The [docs](http://www.mchange.com/projects/c3p0/#cleaning) for 0.9.5.2 indicate that `ComboPooledDataSource` implements `java.lang.AutoCloseable`, but it looks like support was pulled in [`c3p0-0.9.5-pre10`](https://github.com/swaldman/c3p0/blob/master/src/dist-static/CHANGELOG)

**Comment by swaldman** [comment]
Yes, sorry. It was pulled because it led to problems for people running under older Java versions, if I recall. I'm sorry I forgot to update the docs, will do shortly.

**Comment by swaldman** [comment]
(Thanks, by the way!)

**Comment by swaldman** [comment]
`AutoCloseable` will be added again for c3p0-0.10.0, coming soon. That release will require Java 7+

See https://github.com/swaldman/c3p0/commit/a3906341a86c610327aa95c9429e82529ebca9c4
